services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: parametrodospostos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d parametrodospostos"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
