[package]
name = "core_db"
description = "Camada de acesso ao banco de dados compartilhada entre os crates do workspace"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "uuid", "chrono"] }
tokio = { version = "1.52.1", features = ["rt", "macros", "sync", "io-util"] }
uuid = "1.23.1"
